# Generated by Django 2.2.3 on 2019-08-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paris_sportif', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
