# Generated by Django 2.2.3 on 2019-08-01 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paris_sportif', '0003_auto_20190801_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='is_win',
            name='body',
        ),
        migrations.AddField(
            model_name='mise',
            name='is_bet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paris_sportif.bet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mise',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
