# Generated by Django 2.2.3 on 2019-08-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris_sportif', '0004_auto_20190801_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='terminé',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
