# Generated by Django 2.2.3 on 2019-08-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris_sportif', '0007_remove_team_terminé'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='finish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
