# Generated by Django 2.2.3 on 2019-08-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paris_sportif', '0008_team_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=200)),
                ('two', models.CharField(max_length=200)),
                ('finish', models.BooleanField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='finish',
        ),
    ]
