# Generated by Django 2.2.3 on 2019-08-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paris_sportif', '0011_auto_20190802_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='match',
        ),
    ]
